name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:

jobs:
  get-context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        gradle-version: ['8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          gradle-version: ${{ matrix.gradle-version }}
      - name: Build with Gradle
        run: ./gradlew clean build
